[meta]
name = "Diegetic Information Display"
author = "MisfitMaid"
category = "Overlay"
version = "0.2.1"
siteid = 311

[script]
dependencies = ["Camera", "VehicleState"]
optional_dependencies = ["MLHook", "MLFeedRaceData"]
exports = [ "Export.as" ]
shared_exports = [ "ExportShared.as" ]
module = "DID"
